/**
 * COPY MODULE - Main Orchestrator
 *
 * Split-panel layout:
 *   Left  (~20%) → compact scrollable settings sidebar
 *   Right (~80%) → wide results panel with tabs (type → audience → angles)
 *
 * All field rendering is driven by copyConfig.ts — no hardcoded field logic here.
 * Model selection lives in the ResultsPanel header.
 * Audiences and Angles both use the shared ModeListBox component.
 *
 * Generation settings:
 *   - Angles ModeListBox sits directly under the copy type checkboxes
 *   - Audiences ModeListBox sits below Angles
 *
 * Wired to the backend via useCopyGeneration hook.
 * Selection state managed by useSelection hook.
 */

import { useState, useCallback, useEffect, useRef, useMemo } from 'react';
import { PenLine } from 'lucide-react';
import { trpc } from '@/lib/trpc';
import { useSettings } from '@/contexts/AppContext';
import {
  ModeListBox,
  GroupedAnglesList,
  colors,
  typography,
  ContextPanel,
  ThemeSelector,
  createEmptyContextData,
  EnhancedBrandSection,
  DEFAULT_BRAND_TOGGLES,
} from '@/components/shared';
import type { GenerationMode, ListItem, AngleItem, ContextData, ScrapedBusinessData } from '@/components/shared';
import type { SessionReferenceImage } from '@shared/referenceImageIntents';
import type {
  CopyType,
  CopyTypeSelection,
  CopyFormValues,
} from './types';
import { DEFAULT_AUDIENCES } from './types';
import { COPY_SECTIONS, isSectionVisible, buildDefaultFormValues } from './copyConfig';
import { CopyTypeSelector } from './components/CopyTypeSelector';
import { DynamicSection } from './components/DynamicSection';
import { TemplateDropdown } from './components/TemplateDropdown';
import { ReferenceAdsSection } from './components/ReferenceAdsSection';
import type { TemplateEntryData, TemplateApplyPayload } from './components/TemplateDropdown';
import { buildTemplatePopulation, buildTemplateClearUpdates } from './templatePopulator';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ResultsPanel } from './components/ResultsPanel';
import { useCopyGeneration, type GenerateScope } from './useCopyGeneration';
import { useSelection } from './useSelection';
import { useTextModels } from './useTextModels';
import { mapBrandToFormValues, mapScrapedToFormValues } from '@shared/brandTypes';
import { getBrandLogo } from '@shared/brandAssetResolver';
import { SaveBrandButton } from '@/components/shared/SaveBrandButton';

/** A selectable copy framework: name shown in the dropdown, text injected as {{copyFramework}}. */
interface FrameworkOption { name: string; text: string }

/** shadcn Select can't hold an empty-string value, so the "no framework" choice uses a sentinel. */
const FRAMEWORK_NONE = '__none__';

export interface GenerationSettings {
  anglesMode: GenerationMode;
  anglesCount: number;
  audiencesMode: GenerationMode;
  audiencesCount: number;
}

/** Empty default — angles are either entered manually or auto-generated by LLM */
const DEFAULT_ANGLES: AngleItem[] = [];

export function CopyModule() {
  // ── State ──
  const [selectedTypes, setSelectedTypes] = useState<CopyTypeSelection>({
    social_ads: true,
    social_organic: false,
  });

  const [formValues, setFormValues] = useState<CopyFormValues>(buildDefaultFormValues());

  // Audiences — shared across both copy types
  const [audiences, setAudiences] = useState<ListItem[]>(
    DEFAULT_AUDIENCES.map((a) => ({ id: a.id, name: a.name }))
  );

  // Angles — extended with audienceId for audience pairing
  const [angles, setAngles] = useState<AngleItem[]>(DEFAULT_ANGLES);

  // Selected template ID (from the Templates module)
  const [selectedTemplateId, setSelectedTemplateId] = useState<number | undefined>(undefined);

  // Shared context: brand, URL, theme (single source of truth via ContextPanel)
  const [contextData, setContextData] = useState<ContextData>(createEmptyContextData());

  // Reference images for multimodal prompts (selected via EnhancedBrandSection)
  const [sessionReferenceImages, setSessionReferenceImages] = useState<SessionReferenceImage[]>([]);

  // Generation settings — angles & audiences mode (default to auto)
  const [genSettings, setGenSettings] = useState<GenerationSettings>({
    anglesMode: 'auto',
    anglesCount: 3,
    audiencesMode: 'auto',
    audiencesCount: 3,
  });

  // Research toggle — controls whether audience generation includes a research step
  const [researchEnabled, setResearchEnabled] = useState(true);

  // Research outcome from last generation — detailed status from backend.
  // Resets to 'idle' on model change or research toggle.
  type ResearchOutcome = 'idle' | 'success' | 'skipped_not_google' | 'skipped_no_key' | 'error' | 'not_requested';
  const [researchOutcome, setResearchOutcome] = useState<ResearchOutcome>('idle');
  // Human-readable reason when research was skipped or failed
  const [researchSkipReason, setResearchSkipReason] = useState('');

  // Model list — used to check if research model is Google (grounding-capable)
  const { textModels } = useTextModels();


  // ── Copy Generation Hook ──
  const {
    isGenerating,
    progress,
    results,
    resolvedAudiences,
    resolvedAngles,
    generate,
    regenerateCard,
    regenerateBatch,
    duplicateAudience,
    renameAudience,
    duplicateCard,
    updateCardText,
    regeneratingCards,
    error,
    clearError,
    hasResults,
    lastResearchStatus,
    lastResearchError,
  } = useCopyGeneration();

  // ── Selection Hook ──
  const selection = useSelection(results);

  // When auto-generation resolves audiences/angles, update the sidebar lists
  useEffect(() => {
    if (resolvedAudiences.length > 0 && genSettings.audiencesMode === 'auto') {
      setAudiences(resolvedAudiences);
    }
  }, [resolvedAudiences, genSettings.audiencesMode]);

  useEffect(() => {
    if (resolvedAngles.length > 0 && genSettings.anglesMode === 'auto') {
      setAngles(resolvedAngles);
    }
  }, [resolvedAngles, genSettings.anglesMode]);

  // Sync research status from SSE generate flow to research toggle icon state
  useEffect(() => {
    if (lastResearchStatus) {
      setResearchOutcome(lastResearchStatus as ResearchOutcome);
      setResearchSkipReason(lastResearchError ?? '');
    }
  }, [lastResearchStatus, lastResearchError]);

  // ── Handlers ──
  const handleFieldChange = useCallback((fieldId: string, value: string | number) => {
    setFormValues((prev) => ({ ...prev, [fieldId]: value }));
  }, []);

  /** Batch update multiple form fields at once (used by ReferenceAdsSection for re-indexing) */
  const handleBatchChange = useCallback((updates: Record<string, string | undefined>) => {
    setFormValues((prev) => {
      const next = { ...prev };
      for (const [key, val] of Object.entries(updates)) {
        if (val === undefined) {
          delete next[key];
        } else {
          next[key] = val;
        }
      }
      return next;
    });
  }, []);

  /** Map scraped data from ContextPanel to Copy form fields (centralized utility) */
  const handleUrlFetched = useCallback((scraped: ScrapedBusinessData) => {
    const mapped = mapScrapedToFormValues(scraped);
    if (Object.keys(mapped).length > 0) {
      setFormValues((prev) => ({ ...prev, ...mapped }));
    }
  }, []);

  /** Sync ContextPanel changes to Copy form fields (brand → form mapping, theme sync) */
  const handleContextChange = useCallback((newCtx: ContextData) => {
    const prevCtx = contextData;
    setContextData(newCtx);

    // Brand changed (or brand data updated) → map brand fields to form values.
    // Checks both brandId change AND brand object identity to catch
    // refreshBrand updates where brandId stays the same.
    const brandChanged = newCtx.brandId !== prevCtx.brandId;
    const brandDataUpdated = newCtx.brand !== prevCtx.brand;
    if ((brandChanged || brandDataUpdated) && newCtx.brand) {
      const mapped = mapBrandToFormValues(newCtx.brand as Record<string, any>);
      if (Object.keys(mapped).length > 0) {
        setFormValues((prev) => ({ ...prev, ...mapped }));
      }
    }

    // Theme changed → sync to form values
    if (newCtx.seasonEvent !== prevCtx.seasonEvent) {
      setFormValues((prev) => ({ ...prev, season_event: newCtx.seasonEvent }));
    }
    if (newCtx.campaignTheme !== prevCtx.campaignTheme) {
      setFormValues((prev) => ({ ...prev, campaign_theme: newCtx.campaignTheme }));
    }
  }, [contextData]);

  /**
   * Handle brand saved from SaveBrandButton.
   * Refetches the brand from DB and updates contextData so handleContextChange
   * re-maps the brand fields to form values.
   */
  const utils = trpc.useUtils();
  const handleBrandSaved = useCallback(async (brandId: number) => {
    try {
      const fresh = await utils.client.brands.getById.query({ id: brandId });
      if (fresh) {
        // Update contextData with fresh brand → triggers handleContextChange → re-maps form
        setContextData((prev) => ({ ...prev, brandId, brand: fresh }));
      }
    } catch {
      // Silently fail — brand was saved, but refresh failed. Not critical.
    }
  }, [utils]);

  /**
   * Handle template selection/clearing.
   * Populates visible form fields from template entries (reference ads, tonality, instructions, presets).
   * When cleared (entries === null), removes template-populated fields.
   */
  const handleTemplateApply = useCallback(({ templateId, entries }: TemplateApplyPayload) => {
    setSelectedTemplateId(templateId);
    handleTemplateEntries(entries);
  }, []);

  // Remember the exact brief/tonality the last template applied, so that when the
  // template is cleared we can tell whether the user edited those fields by hand
  // afterwards and preserve their manual edits (see buildTemplateClearUpdates).
  const lastAppliedBriefRef = useRef<string>('');
  const lastAppliedTonalityRef = useRef<string>('');

  // Framework dropdown options — sourced from copy templates whose entry subtype
  // is 'framework' (NOT hardcoded). Add a framework in the Templates module and it
  // appears here. Standalone selection: unaffected by applying/clearing templates.
  const copyTemplatesQuery = trpc.templates.list.useQuery({ module: 'copy' });
  const frameworkOptions: FrameworkOption[] = useMemo(() => {
    const list = (copyTemplatesQuery.data ?? []) as Array<{
      name: string;
      entries?: Array<{ category?: string; value?: string }>;
    }>;
    const opts: FrameworkOption[] = [];
    for (const t of list) {
      const fe = (t.entries ?? []).find((e) => e.category === 'framework');
      if (fe) opts.push({ name: t.name, text: fe.value ?? '' });
    }
    return opts;
  }, [copyTemplatesQuery.data]);

  const handleTemplateEntries = useCallback((entries: TemplateEntryData[] | null) => {
    if (entries === null) {
      // Template cleared — remove template-populated fields, but keep brief /
      // tonality if the user manually changed them since the template applied.
      setFormValues((prev) => {
        const briefWasModified =
          ((prev.creativeBrief as string | undefined) ?? '') !== lastAppliedBriefRef.current;
        const tonalityWasModified =
          ((prev.template_tonality as string | undefined) ?? '') !== lastAppliedTonalityRef.current;
        const clearUpdates = buildTemplateClearUpdates(prev, briefWasModified, tonalityWasModified);
        const next = { ...prev };
        for (const [key, val] of Object.entries(clearUpdates)) {
          if (val === undefined) {
            delete next[key];
          } else {
            next[key] = val;
          }
        }
        return next;
      });
      // Reset baseline — there's no longer a template-applied value to compare against.
      lastAppliedBriefRef.current = '';
      lastAppliedTonalityRef.current = '';
    } else {
      // Template selected — populate form fields from entries
      setFormValues((prev) => {
        const { formUpdates } = buildTemplatePopulation(entries, prev);
        // Record what the template applied as the new "unmodified" baseline.
        lastAppliedBriefRef.current = (formUpdates.creativeBrief as string | undefined) ?? '';
        lastAppliedTonalityRef.current = (formUpdates.template_tonality as string | undefined) ?? '';
        const next = { ...prev };
        for (const [key, val] of Object.entries(formUpdates)) {
          if (val === undefined) {
            delete next[key];
          } else {
            next[key] = val;
          }
        }
        return next;
      });
    }
  }, []);



  // Angles list is managed by GroupedAnglesList via onItemsChange
  // (add, remove, copy, drag all handled by the component)

  // Audiences list handlers
  const handleAddAudience = useCallback((name: string) => {
    const id = `audience_${Date.now()}`;
    setAudiences((prev) => [...prev, { id, name }]);
  }, []);

  const handleRemoveAudience = useCallback((id: string) => {
    setAudiences((prev) => prev.filter((a) => a.id !== id));
  }, []);

  // ── Pre-Generate (✨ sparkle button) ──
  const suggestMutation = trpc.copy.suggest.useMutation();

  // Read default Writer Model from Settings → Module Defaults
  const { settings } = useSettings();

  // Reset research state when the configured model changes (e.g. user picks a different model in Settings)
  useEffect(() => {
    setResearchOutcome('idle');
    setResearchSkipReason('');
  }, [settings.defaultCopyResearchModel, settings.defaultCopyMenuIntelligence]);

  /**
   * Validate required fields before any sparkle-generation API call.
   * Throws with a short, readable error naming the missing fields.
   * Runs on frontend to avoid unnecessary API round-trips.
   */
  const validateBeforeGenerate = useCallback(() => {
    const missing: string[] = [];
    if (!String(formValues.business_name ?? '').trim()) missing.push('Business Name');
    if (missing.length > 0) {
      throw new Error(`Fill in: ${missing.join(', ')}`);
    }
    if (!settings.defaultCopyMenuIntelligence) {
      throw new Error('Set a Menu Intelligence model in Settings → Module Defaults');
    }
  }, [formValues, settings.defaultCopyMenuIntelligence]);

  /** Generate angles via AI and fill manual fields (audience-aware) */
  const handleGenerateAngles = useCallback(async (): Promise<AngleItem[]> => {
    validateBeforeGenerate();
    const res = await suggestMutation.mutateAsync({
      type: 'angles',
      count: genSettings.anglesCount,
      formValues,
      // Pass current audiences so backend generates audience-specific angles
      audiences: audiences.length > 0 ? audiences : [],
      ...(settings.defaultCopyMenuIntelligence ? { modelId: settings.defaultCopyMenuIntelligence } : {}),
    });
    // Preserve audienceId from backend response (audience-paired angles)
    const items = ((res as any).items ?? []) as AngleItem[];
    return items;
  }, [suggestMutation, genSettings.anglesCount, formValues, audiences, settings.defaultCopyMenuIntelligence, validateBeforeGenerate]);

  /** Generate audiences via AI and fill manual fields */
  const handleGenerateAudiences = useCallback(async () => {
    validateBeforeGenerate();
    const res = await suggestMutation.mutateAsync({
      type: 'audiences',
      count: genSettings.audiencesCount,
      formValues,
      useResearch: researchEnabled,
      ...(settings.defaultCopyResearchModel ? { researchModelId: settings.defaultCopyResearchModel } : {}),
      ...(settings.defaultCopyMenuIntelligence ? { modelId: settings.defaultCopyMenuIntelligence } : {}),
    });
    // Update research outcome from enriched backend response
    setResearchOutcome((res as any).researchStatus ?? 'not_requested');
    setResearchSkipReason((res as any).researchError ?? '');
    return (res as any).items ?? [];
  }, [suggestMutation, genSettings.audiencesCount, formValues, researchEnabled, settings.defaultCopyResearchModel, settings.defaultCopyMenuIntelligence, validateBeforeGenerate]);

  // Active copy types
  const activeTypes = (Object.keys(selectedTypes) as CopyType[]).filter((t) => selectedTypes[t]);

  // ── Generate Handler (called by ResultsPanel) ──
  const handleGenerate = useCallback(
    (scope: GenerateScope, activeTab: CopyType | null, activeAudience: string, modelId: string) => {
      if (activeTypes.length === 0) return;

      // 1. Respect Toggles for Text Fields
      const finalFormValues = { ...formValues };
      const toggles = { ...DEFAULT_BRAND_TOGGLES, ...contextData.brandToggles };
      
      if (!toggles.useSummary) {
        finalFormValues.business_summary = ''; // Strip if deselected
      }

      // 2. Build Visual Assets payload if toggles are active
      const brand = contextData.brand as Record<string, any> | null;
      const visualAssets: GenerateParams['visualAssets'] = {};
      
      if (toggles.useColors && Array.isArray(brand?.colors)) {
        visualAssets.colors = brand.colors as string[];
      }
      if (toggles.useLogo) {
        const logo = getBrandLogo(brand);
        if (logo) {
          visualAssets.logo = logo.url;
        }
      }
      if (toggles.useReferenceSubjects && sessionReferenceImages.length > 0) {
        visualAssets.referenceImages = sessionReferenceImages.map(img => ({ url: img.url, intent: img.intent }));
      }

      generate({
        copyTypes: activeTypes,
        audiences: {
          mode: genSettings.audiencesMode,
          items: audiences,
          count: genSettings.audiencesCount,
        },
        angles: {
          mode: genSettings.anglesMode,
          items: angles,
          count: genSettings.anglesCount,
        },
        modelId,
        formValues: finalFormValues,
        useResearch: researchEnabled,
        ...(settings.defaultCopyResearchModel ? { researchModelId: settings.defaultCopyResearchModel } : {}),
        scope,
        scopeFilter: {
          type: activeTab ?? activeTypes[0],
          audienceId: activeAudience,
        },
        visualAssets,
      });
    },
    [activeTypes, audiences, angles, genSettings, formValues, generate, researchEnabled, settings.defaultCopyResearchModel, contextData, sessionReferenceImages],
  );

  // ── Regenerate Card Handler ──
  const handleRegenerateCard = useCallback(
    (variationId: string, instruction?: string) => {
      regenerateCard(variationId, formValues, instruction);
    },
    [formValues, regenerateCard],
  );

  // ── Regenerate Batch Handler ──
  const handleRegenerateBatch = useCallback(
    (variationIds: string[], instruction?: string) => {
      regenerateBatch(variationIds, formValues, instruction);
      // Clear selection after batch action
      selection.clearSelection();
    },
    [formValues, regenerateBatch, selection],
  );

  // ── Duplicate Audience Handler ──
  const handleDuplicateAudience = useCallback(
    (audienceId: string, audienceName: string) => {
      duplicateAudience(audienceId, audienceName).then(() => {
        // The hook updates resolvedAudiences, which triggers the useEffect above
        // to update the sidebar audiences list
      });
    },
    [duplicateAudience],
  );

  // ── Rename Audience Handler ──
  const handleRenameAudience = useCallback(
    (audienceId: string, newName: string) => {
      renameAudience(audienceId, newName);
      // Also update the sidebar audiences list immediately
      setAudiences((prev) =>
        prev.map((a) => (a.id === audienceId ? { ...a, name: newName } : a)),
      );
    },
    [renameAudience],
  );

  // ── Save Edits Handler ──
  const handleSaveEdits = useCallback(
    async (
      variationId: string,
      updates: { headline?: string; body?: string; cta?: string; hashtags?: string },
    ) => {
      await updateCardText(variationId, updates);
    },
    [updateCardText],
  );

  return (
    <div className="h-full flex flex-col">
      {/* Module Header */}
      <div className="flex items-center gap-2 mb-3 shrink-0">
        <PenLine className="w-5 h-5" style={{ color: colors.primary }} />
        <h1 className="text-lg font-bold" style={{ color: colors.text }}>
          Copy
        </h1>

        {error && (
          <button
            onClick={clearError}
            className="text-xs px-2 py-0.5 rounded-full cursor-pointer"
            style={{ background: '#fef2f2', color: '#dc2626' }}
            title={error}
          >
            Error (click to dismiss)
          </button>
        )}
      </div>

      {/* Split Panel Layout: 20% settings | 80% results */}
      <div className="flex-1 flex gap-4 overflow-hidden min-h-0">
        {/* ─── LEFT: Compact Settings Sidebar (~20%) ─── */}
        <div
          className="overflow-y-auto space-y-3 min-w-0 pr-1 pt-1"
          style={{ width: '20%', minWidth: '240px', maxWidth: '320px' }}
        >
          {/* Brand / URL — shared ContextPanel (Theme hidden, rendered below) */}
          <ContextPanel
            moduleId="copy"
            value={contextData}
            onChange={handleContextChange}
            onUrlFetched={handleUrlFetched}
            hideTheme
          />

          {/* Business Info & Brand Assets — Replaces dynamic section to include colors/logo/subjects */}
          <EnhancedBrandSection
            contextData={contextData}
            onContextChange={handleContextChange}
            formValues={formValues}
            onFormChange={handleFieldChange}
            referenceImages={sessionReferenceImages}
            onReferenceImagesChange={setSessionReferenceImages}
          />

          {/* Save to Brand — only shows when business_name has value */}
          <SaveBrandButton
            formValues={formValues}
            selectedBrandId={contextData.brandId}
            selectedBrandName={contextData.brand?.name}
            onBrandSaved={handleBrandSaved}
          />

          {/* Copy Type Selector */}
          <CopyTypeSelector selection={selectedTypes} onChange={setSelectedTypes} />

          {/* Template Selection — DB-backed templates from Templates module */}
          <TemplateDropdown
            selectedTemplateId={selectedTemplateId}
            onTemplateApply={handleTemplateApply}
          />

          {/* Offer & Pricing — positioned directly after Templates for logical flow */}
          {COPY_SECTIONS.filter((s) => s.id === 'pricing_offer').map((section) => (
            <DynamicSection
              key={section.id}
              section={section}
              values={formValues}
              selectedTypes={selectedTypes}
              onChange={handleFieldChange}
            />
          ))}

          {/* Creative Brief — free-form user directions for AI generation */}
          <div
            className="rounded-lg border p-3 space-y-2"
            style={{ borderColor: colors.border, background: colors.bgMuted }}
          >
            <label
              className="block"
              style={{
                fontSize: typography.micro,
                fontWeight: typography.semibold,
                textTransform: 'uppercase' as const,
                letterSpacing: '0.05em',
                color: colors.textSecondary,
              }}
            >
              Creative Brief
            </label>
            <textarea
              value={(formValues.creativeBrief as string) ?? ''}
              onChange={(e) => handleFieldChange('creativeBrief', e.target.value)}
              placeholder="Describe what you want to achieve, specific directions, tone preferences…"
              rows={3}
              className="w-full rounded-md border px-2 py-1.5 text-sm transition-colors focus:outline-none focus:ring-1"
              style={{
                borderColor: colors.border,
                background: colors.bgSurface,
                color: colors.text,
                fontSize: typography.sm,
                resize: 'vertical' as const,
              }}
            />
          </div>

          {/* Copy Framework — named structure injected as {{copyFramework}}, kept out of the Creative Brief */}
          <div
            className="rounded-lg border p-3 space-y-2"
            style={{ borderColor: colors.border, background: colors.bgMuted }}
          >
            <label
              className="block"
              style={{
                fontSize: typography.micro,
                fontWeight: typography.semibold,
                textTransform: 'uppercase' as const,
                letterSpacing: '0.05em',
                color: colors.textSecondary,
              }}
            >
              Copy Framework
            </label>
            <Select
              value={(formValues.copyFrameworkName as string) || FRAMEWORK_NONE}
              onValueChange={(v) => {
                const name = v === FRAMEWORK_NONE ? '' : v;
                const opt = frameworkOptions.find((f) => f.name === name);
                handleFieldChange('copyFrameworkName', name);
                handleFieldChange('copyFramework', opt?.text ?? '');
              }}
              disabled={copyTemplatesQuery.isLoading}
            >
              <SelectTrigger className="h-9 text-sm w-full">
                <SelectValue placeholder={copyTemplatesQuery.isLoading ? 'Loading frameworks…' : 'No framework'} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={FRAMEWORK_NONE}>No framework</SelectItem>
                {frameworkOptions.map((f) => (
                  <SelectItem key={f.name} value={f.name}>
                    {f.name}
                  </SelectItem>
                ))}
                {/* Keep a persisted selection visible even if it is not in the current list */}
                {(formValues.copyFrameworkName as string) &&
                  !frameworkOptions.some((f) => f.name === formValues.copyFrameworkName) && (
                    <SelectItem value={formValues.copyFrameworkName as string}>
                      {formValues.copyFrameworkName as string}
                    </SelectItem>
                  )}
              </SelectContent>
            </Select>
            {!copyTemplatesQuery.isLoading && frameworkOptions.length === 0 && (
              <p className="text-xs" style={{ color: colors.textSecondary }}>
                No frameworks yet — create a Copy template with Subtype = Framework in the Templates module.
              </p>
            )}
          </div>

          {/* Theme — rendered after Creative Brief */}
          <ThemeSelector
            seasonEvent={contextData.seasonEvent}
            campaignTheme={contextData.campaignTheme}
            onSeasonChange={(seasonEvent) => setContextData((prev) => ({ ...prev, seasonEvent }))}
            onCampaignThemeChange={(campaignTheme) => setContextData((prev) => ({ ...prev, campaignTheme }))}
          />

          {/* Audiences — ModeListBox with research toggle (above Angles) */}
          <ModeListBox
            label="Audiences"
            mode={genSettings.audiencesMode}
            onModeChange={(m) => setGenSettings((prev) => ({ ...prev, audiencesMode: m }))}
            items={audiences}
            onAddItem={handleAddAudience}
            onRemoveItem={handleRemoveAudience}
            onItemsGenerated={setAudiences}
            placeholder="Add audience…"
            autoCount={genSettings.audiencesCount}
            onAutoCountChange={(c) => setGenSettings((prev) => ({ ...prev, audiencesCount: c }))}
            autoHint={`AI will generate ${genSettings.audiencesCount} audience${genSettings.audiencesCount !== 1 ? 's' : ''} based on your brief`}
            onGenerate={handleGenerateAudiences}
            researchEnabled={researchEnabled}
            onResearchToggle={(enabled) => {
              setResearchEnabled(enabled);
              // Reset outcome when user toggles — avoids stale grey icon
              setResearchOutcome('idle');
              setResearchSkipReason('');
            }}
            researchAvailable={
              // Research is only possible if a Google model is configured as research model
              // (grounding requires Gemini). Check the model provider from the models list.
              (() => {
                const researchModelId = settings.defaultCopyResearchModel || settings.defaultCopyMenuIntelligence || '';
                if (!researchModelId) return false;
                const model = textModels.find((m) => m.id === researchModelId);
                return model?.provider === 'google';
              })()
            }
            researchStatus={
              researchOutcome === 'idle' ? 'idle'
                : researchOutcome === 'success' ? 'success'
                  : 'failed'
            }
            researchSkipReason={researchSkipReason}
          />

          {/* Angles — Grouped by audience with drag-drop, copy, per-group add */}
          <GroupedAnglesList
            mode={genSettings.anglesMode}
            onModeChange={(m) => setGenSettings((prev) => ({ ...prev, anglesMode: m }))}
            items={angles}
            onItemsChange={setAngles}
            audiences={audiences}
            autoCount={genSettings.anglesCount}
            onAutoCountChange={(c) => setGenSettings((prev) => ({ ...prev, anglesCount: c }))}
            onGenerate={handleGenerateAngles}
            onItemsGenerated={setAngles}
          />

          {/* Reference Ads — dynamic list section (rendered separately from DynamicSection) */}
          <ReferenceAdsSection
            values={formValues}
            onChange={handleFieldChange}
            onBatchChange={handleBatchChange}
          />

          {/* Dynamic Sections from Config (excluding Business Info, Reference Ads, and Theme — handled by ContextPanel) */}
          {COPY_SECTIONS.filter(
            (s) => s.id !== 'business_info' && s.id !== 'reference_ads' && s.id !== 'seasonal_campaign' && s.id !== 'pricing_offer' && isSectionVisible(s, selectedTypes),
          ).map((section) => (
            <DynamicSection
              key={section.id}
              section={section}
              values={formValues}
              selectedTypes={selectedTypes}
              onChange={handleFieldChange}
            />
          ))}

          {/* Bottom spacer */}
          <div className="h-4" />
        </div>

        {/* ─── RIGHT: Wide Results Panel (~80%) ─── */}
        <div
          className="flex-1 overflow-hidden flex flex-col min-w-0"
          style={{
            background: colors.bgMuted,
            borderRadius: '0.75rem',
            border: `1px solid ${colors.border}`,
            padding: '1rem',
          }}
        >
          <ResultsPanel
            results={results}
            isGenerating={isGenerating}
            progress={progress}
            selectedTypes={selectedTypes}
            audiences={audiences}
            onGenerate={handleGenerate}
            onRegenerateCard={handleRegenerateCard}
            onRegenerateBatch={handleRegenerateBatch}
            onDuplicateAudience={handleDuplicateAudience}
            onRenameAudience={handleRenameAudience}
            onDuplicateCard={duplicateCard}
            onSaveEdits={handleSaveEdits}
            regeneratingCards={regeneratingCards}
            hasRealResults={hasResults}
            selection={selection}
            brandId={contextData.brandId}
            brandName={(contextData.brand as any)?.name}
            projectId={(contextData.brand as any)?.projectId}
            brandClientEmail={(contextData.brand as any)?.clientEmail}
            brandLogoUrl={getBrandLogo(contextData.brand as any)?.url}
          />
        </div>
      </div>
    </div>
  );
}
