/**
 * COPY MODULE - Type Definitions
 *
 * All types for the config-driven social media copy generator.
 * These types power the dynamic form rendering and result display.
 */

// ============================================
// Copy Type Identifiers
// ============================================

/** Supported copy types — extend this union to add new types */
export type CopyType = 'social_ads' | 'social_organic';

/** Human-readable labels for each copy type */
export const COPY_TYPE_LABELS: Record<CopyType, string> = {
  social_ads: 'Social Ads',
  social_organic: 'Social Organic',
};

// ============================================
// Field Configuration
// ============================================

/** Supported input types for dynamic field rendering */
export type FieldInputType =
  | 'text'
  | 'textarea'
  | 'number'
  | 'select'
  | 'url'
  | 'slider'
  | 'dynamic_list';

/** Visibility rule per copy type */
export type FieldVisibility = 'always' | 'social_ads' | 'social_organic';

/** Whether a field is required, optional, or hidden for a given copy type */
export type FieldRequirement = 'required' | 'optional' | 'hidden';

/** Re-export SelectOption from shared — single source of truth */
export type { SelectOption } from '@/components/shared/copySettingsConfig';
import type { SelectOption } from '@/components/shared/copySettingsConfig';

/** Full field definition — the building block of the config */
export interface CopyFieldConfig {
  /** Unique key used as form state key */
  id: string;
  /** Display label */
  label: string;
  /** Input type to render */
  inputType: FieldInputType;
  /** Placeholder text */
  placeholder?: string;
  /** Options for select fields */
  options?: SelectOption[];
  /** Default value */
  defaultValue?: string | number;
  /** Min/max for number/slider fields */
  min?: number;
  max?: number;
  step?: number;
  /** Which copy types this field applies to */
  applicableTo: FieldVisibility;
  /** Requirement level per copy type (defaults to optional if omitted) */
  requirements?: Partial<Record<CopyType, FieldRequirement>>;
  /** Help text shown below the field */
  helpText?: string;
  /** Width hint: 'full' = 100%, 'half' = 50% */
  width?: 'full' | 'half';
  /**
   * For dynamic_list fields: the prefix used for indexed keys in formValues.
   * E.g., prefix 'reference_ad' → keys reference_ad_0, reference_ad_1, …
   */
  dynamicListPrefix?: string;
}

// ============================================
// Section Configuration
// ============================================

/** A collapsible section that groups related fields */
export interface CopySectionConfig {
  /** Unique section key */
  id: string;
  /** Display title */
  title: string;
  /** Which copy types this section applies to */
  applicableTo: FieldVisibility;
  /** Whether the section starts collapsed */
  defaultCollapsed: boolean;
  /** Fields inside this section */
  fields: CopyFieldConfig[];
}

// ============================================
// Audience Configuration
// ============================================

/** A target audience definition */
export interface CopyAudience {
  id: string;
  name: string;
}

/** Empty default — audiences are either entered manually or auto-generated by LLM */
export const DEFAULT_AUDIENCES: CopyAudience[] = [];

// ============================================
// Form State
// ============================================

/** Dynamic form values — keys match CopyFieldConfig.id */
export type CopyFormValues = Record<string, string | number | undefined>;

/** Which copy types are currently selected */
export type CopyTypeSelection = Record<CopyType, boolean>;

/** Model selection per copy type */
export type ModelSelectionPerType = Partial<Record<CopyType, string>>;

// ============================================
// Generation Results
// ============================================

/** A single generated copy variation (now represents an Angle) */
export interface CopyVariation {
  id: string;
  copyType: CopyType;
  audienceId: string;
  /** Named angle label, e.g. "Romantisk", "Kärleksfull", "Akut" */
  angleName?: string;
  headline: string;
  body: string;
  cta?: string;
  hashtags?: string[];
  /** Short link description displayed below headline (Facebook-style) */
  description?: string;
  modelUsed: string;
  createdAt: Date;
}

/** Results grouped by copy type */
export type CopyResults = Partial<Record<CopyType, CopyVariation[]>>;

/** Get variations filtered by audience */
export function filterByAudience(variations: CopyVariation[], audienceId: string): CopyVariation[] {
  return variations.filter((v) => v.audienceId === audienceId);
}

// ============================================
// Offer Template
// ============================================

/** Pre-built offer template for quick fill */
export interface OfferTemplate {
  id: string;
  name: string;
  applicableTo: CopyType;
  fields: Partial<CopyFormValues>;
}
